pres/Auction.Web/Models/Cart.cs
namespace Auction.Web.Models
{
    public class Cart
    {
        public int OrderId { get; }
        public int TotalCount { get; set; }
        public decimal TotalPrice { get; set; }
        public Cart(int orderId)
        {
            OrderId = orderId;
            TotalCount = 0;
            TotalPrice = 0m;
        }
    }
}

pres/Auction.Web/Models/ErrorViewModel.cs
namespace Auction.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

pres/Auction.Web/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace Auction.Web.Models
{
    public class LoginModel
    {
        [Required]
        [EmailAddress]
        public string Login { get; set; }
        [Required]
        [MinLength(8)]
        public string Password { get; set; }
    }
}

pres/Auction.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Auction.Web.Models;
namespace Auction.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthServise _authServise;
        private readonly IAkkRepos _akkRepos;
        public AuthController(IAuthServise authServise,IAkkRepos akkRepos)
        {
            _authServise = authServise;
            _akkRepos = akkRepos;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(LoginModel model)
        {
            if (string.IsNullOrEmpty(model.Login) || string.IsNullOrEmpty(model.Password))
            {
                return BadRequest("Invalid login or password");
            }
            var user = _authServise.GetUserByLogin(model.Login);
            if (user == null)
            {
                return NotFound("User not found");
            }
            if (_authServise.Login(model.Login, model.Password))
            {
                return RedirectToAction("Index", "Home");
            }
            return BadRequest("Invalid login or password");
        }
        [HttpPost]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

pres/Auction.Web/Controllers/HomeController.cs
using Auction.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
namespace Auction.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

pres/Auction.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
namespace Auction.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly SlotServes slotServes;
        public SearchController(SlotServes slotServes)
        {
            this.slotServes = slotServes;
        }
        public IActionResult Index(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                var slots1 = slotServes.GetAllByQuery(null);
                return View(slots1);
            }
            var slots = slotServes.GetAllByQuery(query);
            return View(slots);
        }
    }
}

pres/Auction.Web/Controllers/SerchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Auction.Web.Controllers
{
    public class SerchController : Controller
    {
        private readonly ISlotRepos slotRepos;
        public SerchController(ISlotRepos slotRepos)
        {
            this.slotRepos = slotRepos;
        }
        public IActionResult Index(string query)
        {
            var slots = slotRepos.GetAllByTitle(query);
            return View(slots);
        }
    }
}

pres/Auction.Web/Controllers/SlotController.cs
using Microsoft.AspNetCore.Mvc;
namespace Auction.Web.Controllers
{
    public class SlotController : Controller
    {
        private readonly ISlotRepos slotRepos;
        private readonly IAuthServise _authServise;
        public SlotController(ISlotRepos slotRepos, IAuthServise authServise)
        {
            this.slotRepos = slotRepos;
            _authServise = authServise;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            Slot slot = slotRepos.GetById(id);
            return View(slot);
        }
    }
    public enum SlotStatus
    {
        Active,
        Reserved
    }
}

pres/Auction.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Интернет-Аукцион";
}
<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Название</th>
            <th scope="col">Теги</th>
            <th scope="col">Начальная стоймость</th>
            <th scope="col">минимальная ставка</th>
            <th scope="col">Цена на данный момент</th>
            <th scope="col">Статус</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td ></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
    </tbody>
</table>

pres/Auction.Web/Views/Search/Index.cshtml
@model Slot[]
@{
    ViewData["Title"] = "Результаты поиска";
}
<h1>Результаты поиска</h1>
@if (Model.Length == 0)
            {
                <p>Ничего не найдено</p>
            }
            else
            {
            <ul>
                @foreach (var slot in Model)
                 {
                    <li><a href="@Url.Action("Index","Slot",new {id= slot.Id })">@slot.Title</a></li>
                 }
            </ul>
            }

pres/Auction.Web/Views/Serch/Index.cshtml
@model IEnumerable<Auction.Slot>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

pres/Auction.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Интернет-Аукцион</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Интернет-Аукцион</a>
            <form class="form-inline my-2 my-lg-0" action="@Url.Action("Index", "Search")" method="get">
                <input class="form-control mr-sm-2" type="search" name="query" placeholder="Теги или название" />
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Искать</button>
            </form>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Выход</a>
                <a class="nav-link" asp-controller="Home" asp-action="Index">Мои слоты</a>
            }
            else
            {
                <a class="nav-link" asp-controller="Auth" asp-action="Login">Вход</a>
            }
        </nav>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

pres/Auction.Web/Views/Slot/Index.cshtml
@model Slot
@{
    ViewData["Title"] = Model.Title;
}
<h1>@Model.Title</h1>
<p><strong>@Model.Tegs</strong></p>
<p>@Model.Description</p>
<p>Начальная ставка  <strong>@Model.InitialPrice</strong></p>
<p>Минимальная ставка  <strong>@Model.MinBet</strong></p>
<form action="@Url.Action("AddItem","Order")" method="post">
    <input type="hidden" name="id" value="@Model.Id" />
    <button class="btn btn-success"type="submit">На аукцион</button>
</form>